version: "3"

services:
  frontend:
    build: 
      context: .
      dockerfile: front-end/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: back-end/Dockerfile
    ports:
      - "4000:4000"
